quotes_project/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
]

quotes_project/quotes_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_project/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=25, null=False, unique=True)
    born_date = models.CharField(max_length=25, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.fullname}'

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'
    
class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.quote}'

quotes_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(max_length=50, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class AuthorForm(ModelForm):
    
    fullname = CharField(max_length=25, required=True, widget=TextInput())
    born_date = CharField(max_length=25, required=True, widget=TextInput())
    born_location = CharField(max_length=100, required=True, widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all())
    quote = CharField(max_length=5000, required=True, widget=TextInput)

    class Meta:
        model = Quote
        fields = ['author', 'quote']
        exclude = ['tags']

quotes_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from quotes.forms import TagForm, AuthorForm, QuoteForm
from .models import Author, Quote, Tag

# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/author.html', {'form': form})
        
    return render(request, 'quotes/author.html', {'form': AuthorForm()})

def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_authors = Author.objects.filter(fullname__in=request.POST.getlist('authors'))
            for author in choice_authors.iterator():
                new_quote.authors.add(author)
            
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/quote.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'quotes/quote.html', {"authors": authors, "tags": tags, 'form': QuoteForm()})

def author_detail(request, pk):
    post = get_object_or_404(Author, pk=pk)
    context = {
        'post': post,
        'fullname': post.fullname,
        'description': post.description,
        'born_date': post.born_date,
        'born_location': post.born_location,

    }

    return render(request, 'quotes/about-author.html', context)

quotes_project/quotes/templates/quotes/about-author.html
{% extends "quotes/base.html" %}

{% block content %}

<main class="container">

    <h1>{{fullname}}</h1>
    <p>{{born_date}}</p>
    <p>{{born_location}}</p>
    <p>{{description}}</p>


</main>
{% endblock %}

quotes_project/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button class="btn btn-dark" type="submit">Submit</button>
        <button class="btn btn-dark" type="reset">Reset</button>
    </div>
</form>
{% endblock %}

quotes_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" 
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Quotes</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
        </div>
    </div>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <li class="list-group-item mb-3">Welcome <b>{{ user.username }}!</b></li>
        <ul class="d-flex flex-column mb-3">
            <li class="list-group-item"><a class="btn btn-primary mb-3" href="{% url 'quotes:quote' %}" role="button">Add Quote</a></li>
            <li class="list-group-item"><a class="btn btn-primary mb-3" href="{% url 'quotes:tag' %}" role="button">Add Tag</a></li>
            <li class="list-group-item"><a class="btn btn-primary mb-3" href="{% url 'quotes:author' %}" role="button">Add Author</a></li>
            <li class="list-group-item"><a class="btn btn-primary mb-3" href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul class="d-flex flex-column mb-3">
            <li class="list-group-item mb-3"><a class="btn btn-primary" href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li class="list-group-item"><a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>
        {% block content %}
        {% endblock %}
    
    </main>
</body>
</html>

quotes_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}
{% load extract %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                <p>Tags: <small class="tag">
                    {{ quote.tags|tags }}
                </small></p>
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
            
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"><span aria-hidden="true">←</span> Previous</a>
                </li>
                
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
                </li>
                
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

quotes_project/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Select author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.id}}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
        <label>Enter the quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes_project/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div class="mb-3" style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button class="btn btn-dark" type="submit">Submit</button>
        <button class="btn btn-dark" type="reset">Reset</button>
    </div>
</form>

{% endblock %}